[package]
name = "bingo_gameservice"
version.workspace = true
edition = "2024"

[[bin]]
name = "gameservice"
path = "main.rs"

[dependencies]
bingolib = { path = "../bingolib" }
chrono = { version = "0.4.44", features = ["serde"] }
colog = "1.4.0"
dotenv = "0.15.0"
lapin = "4.1.0"
log = "0.4.29"
reqwest = { version = "0.13.2", features = ["json"] }
rosu-v2 = "0.11.0"
serde = "1.0.228"
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros"] }
