[package]
name = "bingo_api"
version.workspace = true
edition = "2024"

[lib]
path = "lib.rs"

[[bin]]
name = "api"
path = "main.rs"

[dependencies]
axum = "0.8.4"
bingolib = { path = "../bingolib" }
chrono = { version = "0.4.41", features = ["serde"] }
dotenv = "0.15.0"
env_logger = "0.11.9"
juniper = { version = "0.16.2", features = [
    "chrono",
    "chrono-tz",
    "schema-language",
] }
juniper_axum = "0.2.0"
log = "0.4.27"
serde = "1.0.219"
serde_json = "1.0.142"
sqlx = { version = "0.8.6", default-features = false, features = [
    "chrono",
    "runtime-tokio",
    "migrate",
    "macros",
    "postgres",
] }
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
